name: LaTeX Action
on: [push]
jobs:
  some:
    runs-on: ubuntu-latest
    steps:
      - uses: xu-cheng/latex-action@v2
        with:
          # The root LaTeX file to be compiled
          root_file: main.tex
