name: LaTeX Action
on: [push]
jobs:
  Compile-LaTeX:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - uses: xu-cheng/latex-action@v2
        with:
          # The root LaTeX file to be compiled
          root_file: main.tex
          working_directory: test/
